title: Omid Pakdel
url: "https://omidpakdel.github.io"
baseurl: ""

bio-page-label: About
theme-home: theme-home-builtin-1.html
theme-projects: theme-projects-builtin-1.html
theme-essays: theme-essays-builtin-1.html
theme-bio: theme-bio-builtin-2.html

rouge-theme: igorpro

markdown: kramdown
include: [_data]
